### ISSUE TITLE
Question: Link + URL

### ISSUE THREAD

**Issue by hawkerm** [mrlacey/CommentLinks#31]
Was just adding a 'link' to my text file and was surprised when the extension came up:

![image](https://user-images.githubusercontent.com/8959496/126916631-33f524a6-70fa-4289-ba0f-07a2eb0ef8aa.png)

Was basically just part of my document, e.g.

```
For more info, click this link: https://github.com/
```

VS of course allows me to just click the link. Does it make sense for the CommentLink button to appear in this case? Should it open the link anyway clicking on it? Or would it make sense to not show it in this case?

Curious on others thoughts.

**Comment by mrlacey** [comment]
I'm open to making it work either way:
- detect the HTTP(s) link and not show the button
or
- have the button open the link in the default browser.


---
However, if it was my document I'd change the text from your example though.
Instead, I'd have something like:

```ascii
More info at https://github.com/
```

I'd do this because:
- The example screenshot shows this in a txt document and so isn't always clickable.
- people know they can click on links. They don't need to be told.
- people know that text that looks like a URL, is blue, and is underlined; is a link and can be clicked on go to that location
- people know that if something looks like a URL they can always put it into a browser. 
- The "go to this link: xxx.example.com" style comment reminds me of the [click here](https://mrlacey.com/) style link that is rightly criticized as being far from ideal.

**Comment by hawkerm** [comment]
Yeah, in this specific case, it's about an example for being able to click in links in a component. But in the general case, makes sense.

Maybe having the button there is a good reminder of just leaving out more archaic terminology from the 90s... 😋

Therefore, at least having option 2 where it'll open the link could be good.

**Comment by mrlacey** [comment]
v2.6 should now open a URI (in the default browser) when you click on the button :)

**Comment by hawkerm** [comment]
Was just clicking a link in the newly updated 2.6 version here:

```cs
       private readonly Range _targetRange = new Range(2, 5, 2, 10); // See MarkerData - link:MainPage.xaml.cs:MarkerData
```
https://github.com/hawkerm/monaco-editor-uwp/blob/cf644d83b8d3eb21cd51ac94bfac100d4fddc945/MonacoEditorTestApp/Helpers/EditorCodeActionProvider.cs#L17

And it tried to open the store? 😋

![image](https://user-images.githubusercontent.com/8959496/129440345-3de40df4-3550-492b-839e-18b3598d8701.png)

If I put quotes around the filename: `link:"MainPage.xaml.cs":MarkerData` it'll go to the file, but won't search for the text (as expected based on how quotes should work I think), but then if I put the whole thing in quotes: `link:"MainPage.xaml.cs:MarkerData"` it still doesn't work.

Is the Uri processor maybe thinking `MainPage.xaml.cs:MarkerData` is a domain name with a port?

**Comment by mrlacey** [comment]
:(

**Comment by mrlacey** [comment]
I've just uploaded 2.7 which should have a suitable fix.
That'll teach me to rush out updates without fully testing.

**Comment by hawkerm** [comment]
I'll give it a whirl and let you know, thanks!

**Comment by hawkerm** [comment]
Works now, thanks!
