### ISSUE TITLE
2.9 Allow navigating higher within the same file.

### ISSUE THREAD

**Issue by markyoung2u** [mrlacey/CommentLinks#37]
1. Matt, how does it work now in 2.9? It used to always search forward and experimenting make me thing it just starts from top of file, not where the link might be? I put several identical links and they all point to the first one. Is this the intended behavior?
2.  If I type link: in a .txt file it should (used to) show the link icon. Now even if I type a full ink it does not iconize and become functional until I type // before it. Yet links already in the same file work w/o any // comment. Older version would not iconize if link starts in column 1 but this version does not iconize if starting in col2, either. If I save a line in column1 with link:DiskTheory.txt6133, close file, then reopen, the icon is not shown until I insert a space in column1 (same as older versions, OK with this, just trying to describe fully).

**Comment by mrlacey** [comment]
> 1. Matt, how does it work now in 2.9? It used to always search forward and experimenting make me thing it just starts from top of file, not where the link might be? I put several identical links and they all point to the first one. Is this the intended behavior?

The original behavior was to search from the link downwards in the file. This was never a deliberate choice, it was just simplest to implement.
Recently I was asked to make it so that it would be able to find links earlier in the file also.

I'm open to suggestions about revising this behavior further. (I don't use links within the same file, only between files, and so don't know what will "feel" best.)

What would be better?
1. A configurable setting to enable always searching from the start of the file vs searching below the link?
2. Being able to add something to a link to indicate a search direction, e.g. `link:thisfile.ext:something^` (to indicate searching from the start of the file.)
3. Something else? Or a combination of 1 & 2?




> 2. If I type link: in a .txt file it should (used to) show the link icon. Now even if I type a full ink it does not iconize and become functional until I type // before it. Yet links already in the same file work w/o any // comment. Older version would not iconize if link starts in column 1 but this version does not iconize if starting in col2, either. If I save a line in column1 with link:DiskTheory.txt6133, close file, then reopen, the icon is not shown until I insert a space in column1 (same as older versions, OK with this, just trying to describe fully).

I'm not sure I fully understand this

**Comment by markyoung2u** [comment]
Originally I thought CL should always search from top of file downward, and skip any text actually inside a CL.  In other words CL should not find any text that is inside a link e,g, link:filespec:"text". That would provide a way to point to both before and after the current link line in a file. A configurable setting option would be OK, but seems to be unnecessary. I have quite a bit of docs that use the older "find forward from the link" method so these links are now broken. I guess specifying the direction of search in the CL would be the best. For me the default should be down and if you want to go up in the same file use something like ^. In fact, why even specify a filespec at all if the link is meant to be in the same file? Maybe link::text to specify down in same file and link:^:text to specify up (would this actually mean from the top of the file?)

**Comment by mrlacey** [comment]
> in a .txt file these lines did not display a green icon: Zoom auto-numbering is supported here: link:cPcieSSD.cpp:"GUESSING: Slot number" // Zoom auto-numbering is supported here: link:cPcieSSD.cpp:"GUESSING: Slot number" This one did: // Zoom auto-numbering is supported here: //link:cPcieSSD.cpp:"GUESSING: Slot number"

I'm not able to reproduce what you describe here:
![image](https://user-images.githubusercontent.com/189547/172025065-2b4be818-7823-45ea-b504-22975d156a03.png)

The code is looking for either "//link" or any whitespace character followed by "link"

**Comment by mrlacey** [comment]
> Originally I thought CL should always search from top of file downward, and skip any text actually inside a CL. In other words CL should not find any text that is inside a link e,g, link:filespec:"text". That would provide a way to point to both before and after the current link line in a file. A configurable setting option would be OK, but seems to be unnecessary. I have quite a bit of docs that use the older "find forward from the link" method so these links are now broken. I guess specifying the direction of search in the CL would be the best. For me the default should be down and if you want to go up in the same file use something like ^. In fact, why even specify a filespec at all if the link is meant to be in the same file? Maybe link::text to specify down in same file and link:^:text to specify up (would this actually mean from the top of the file?)

I think there are two things to do here:

1. Firstly, I can add a setting to enable always searching below the line containing the link. This will enable you to keep using the links you've created as before.

Let me know if this will be useful.

2. Please help me understand why you'd want to be able to link to one of many possible places in a file. 
 
If there are multiple possible places within a file (especially the same file) having a single link to get there doesn't seem the most helpful. Why would you not want to know about all the possible places to go (or instances of something) in the same file.
If a file's contents is likely to change a lot so that linking to a line number isn't appropriate, I'm not convinced that search from a particular point will also always be a good approach.
The intent behind this extension was originally about navigating between files. The ability to jump to a specific point in a file was really only an added extra.
At the moment I'm not seeing a good reason to be able to have a link that navigates to the first instance of something within a file (from whatever point) when there are potentially lots of instances of that string.
There may be one but I can't think what it might be.
Given a scenario where you want to know about all possible instances of a string in a file (so you can navigate to one of them) isn't Visual Studio's built-in "Find in file" or "highlight all instances of the selected text" functionality sufficient?
I'm not ruling out making any change here, I want to understand what you're ultimately trying to achieve so that we can work out the best solution.

**Comment by markyoung2u** [comment]
1.  Yes it would be useful to have a setting to enable searching below. However, it is much more useful to have the links work in some specific way and don't suddenly change behavior making the links inoperable, as CL 2.8 did. Not sure how that setting would be used, but it's best if it's in the actual link so you can make any link work (search in the right direction) instead of some setting that always searches in one direction only, which would not be useful
  2.  I will send a text file link example of where I use links that search downward, in a separate email

Mark

**Comment by markyoung2u** [comment]
I don't feel comfortable sharing the text file as it has some sensitive data - I have a work.txt in an ADDF project and a workEpsa.txt in an ePSA project. I found the failing behavior in each "works" if the file is viewed from the other project. This means for workEpsa.txt which is a file in the ePSA project, that the 1st link below cause CL to find "(1)" in the table of contents, not further done in the file. But if I open workEpsa.txt in project ADDF where it is not part of that project, then clicking on the "(1)" link works and searches downwards. Same is true if I open work.txt in project ePSA - the links work. 
It's as if the search direction is different if the file is not part of the project?
== Other links:
  link:c:\tc2\s\ADDF\Disk\work.txt
  link:c:\tc2\s\ADDF\Disk\DiskTheory.txt

== Table of Contents:
  link:workEpsa.txt:(1) Sn Unknown for xx
  link:workEpsa.txt:(2) xx Tape model "" for ULTRIUM-HH8 TBU 
  link:workEpsa.txt:(3) xx fw update
.. etc

== Numbered items:
=================================================
(1) Sn Unknown for xx
... etc

=================================================
(2) xx Tape model "" for ULTRIUM-HH8 TBU 
... etc

=================================================
(3) xx fw update
  FW Test called from
    Link:cDiskNvmeCmn.cpp:"pcDriveEFI->fFirmwareTest"
  Firmware test
    link:cDiskNvmeCmn.cpp:"ADDF_RC cNVMeDisk::fFirmwareTest"
  FW Test 1st change
    link:cDiskNvmeCmn.cpp:"// Get Firmware Slot"

**Comment by mrlacey** [comment]
> 1. Yes it would be useful to have a setting to enable searching below. However, it is much more useful to have the links work in some specific way and don't suddenly change behavior making the links inoperable, as CL 2.8 did. Not sure how that setting would be used, but it's best if it's in the actual link so you can make any link work (search in the right direction) instead of some setting that always searches in one direction only, which would not be useful 

I suggested adding this as a way to help you out as I'd introduced a change that accidentally broke you. If you're more interested in solving the general problem then great, let's focus on that.
It was never my intention to break anything and I'm sorry that was the case for you.
This extension has very few users and I was expecting the change introduced to have caused such a problem. 

It's to avoid any such further issues for other people that I'm so interested in fully understanding your scenario before looking at possible solutions.

**Comment by mrlacey** [comment]
> I don't feel comfortable sharing the text file as it has some sensitive data - I have a work.txt in an ADDF project and a workEpsa.txt in an ePSA project. I found the failing behavior in each "works" if the file is viewed from the other project. This means for workEpsa.txt which is a file in the ePSA project, that the 1st link below cause CL to find "(1)" in the table of contents, not further done in the file. But if I open workEpsa.txt in project ADDF where it is not part of that project, then clicking on the "(1)" link works and searches downwards. Same is true if I open work.txt in project ePSA - the links work. It's as if the search direction is different if the file is not part of the project? == Other links: link:c:\tc2\s\ADDF\Disk\work.txt link:c:\tc2\s\ADDF\Disk\DiskTheory.txt
> 
> == Table of Contents: link:workEpsa.txt:(1) Sn Unknown for xx link:workEpsa.txt:(2) xx Tape model "" for ULTRIUM-HH8 TBU link:workEpsa.txt:(3) xx fw update .. etc
> 
> # == Numbered items:
> (1) Sn Unknown for xx ... etc
> 
> ================================================= (2) xx Tape model "" for ULTRIUM-HH8 TBU ... etc
> 
> ================================================= (3) xx fw update FW Test called from Link:cDiskNvmeCmn.cpp:"pcDriveEFI->fFirmwareTest" Firmware test link:cDiskNvmeCmn.cpp:"ADDF_RC cNVMeDisk::fFirmwareTest" FW Test 1st change link:cDiskNvmeCmn.cpp:"// Get Firmware Slot"

From what I understand of this, you have a file with a set of external links at the top. Below that, you have a TOC with links to go further in the same document, and then you have the document content which may also include links to other documents.

I'm not seeing where or why you'd have links in the middle of a document that goes to some text that would exist above and below the link. and so you need the link to differentiate.

**Comment by markyoung2u** [comment]
Your understanding is correct. The external links work OK, the TOC links jump to themselves, not a similar line farther down in the file. Note "link:workEpsa.txt:(1) Sn Unknown for xx" points to just "(1)" and the failing cases causes that line to be centered and has the white box drawn. It should jump to the line under Numbered Items "(1) Sn Unknown for xx" (note the "... etc" was on a line below but after I clicked on the Comment button it seemed to join the 2 lines together). Just noting that "(1)" there are only 2 lines with "(1)" and the first is the link and the second is the link target. It seems that CL is doing the wrong thing (search from top) when the file (workEPSA.txt) exists in the project (ADDF.vcxproj)
![image](https://user-images.githubusercontent.com/16338715/172256179-5fcf5a65-8140-406a-b076-2bd4cbcbc7b1.png)
but does the right thing (old way prior to CL 2.8: searching forward from current position ) when the file does not exist in the project (ePSA.vcxproj). So some new change to "need the link to differentiate" seems only half the fix as it should fix the 1st case, but I can't even guess about the 2nd case.
![image](https://user-images.githubusercontent.com/16338715/172256894-71fd9a68-10b3-4ea9-a764-f186a0b97f22.png)

**Comment by mrlacey** [comment]
> Your understanding is correct. The external links work OK, the TOC links jump to themselves, not a similar line farther down in the file. 


Aah, "Jumping to themselves" isn't something you've mentioned before.
I wondered if it could be the brackets in the search term so created a quick test. It's not this, but....

![image](https://user-images.githubusercontent.com/189547/172260455-bdf76b9b-d84b-4a81-9683-5cba74c5f7ee.png)

In the above image, I click on the second link button and nothing happens (because of a typo) but notice that there's a message at the bottom of the screen saying that the text couldn't be found. **Do you get this message?**


You say that when it fails to jump to the correct line it jumps to the line containing the link. **Is this definitely the case?** Can you please retest this. Put the line focus on a very different line, click on a broken link button and then verify which line has focus.


**Does it only fail to work correctly immediately after you've typed (or pasted) the link text? Or does it also fail to work if you restart VS and then open the file and click the button?**
(I've seen a potential issue where an earlier version of the search term is being cached for too long when the search text is being typed.)

**Also, are you sure the file has been saved before clicking on the link?**




> ... but after I clicked on the Comment button it seemed to join the 2 lines together). 

I don't know what you mean by "it seemed to join the 2 lines together". 
Is it modifying the text within the editor? Either by removing line breaks, selecting text over multiple lines, or something else?

A simple example of text that doesn't work and so allows me to reproduce what you're seeing will be much more helpful than a description of the text and guesses about what might be going wrong.

**Comment by mrlacey** [comment]
v2.11 has just been released and supports using a new shorthand syntax to navigate/search up within the same file.

A link like (`link:^:"search term"`) will go to the first instance of the search term above the line with the link.

Hopefully, this will help with your project.
It works as you describe above but it does not wrap around and continue searching from the bottom of the file if the search term is not found.
