### ISSUE TITLE
Request: When using the link:run> format, replace $(ItemPath) with the active file

### ISSUE THREAD

**Issue by hakakou** [mrlacey/CommentLinks#45]
Perhaps so something like this could work:
```
// Compare link:run>"mp.bat $(ItemPath)"
```

$(ItemPath) for me is the most useful, but to take this even further you could use the same tags the external tools use:
https://docs.microsoft.com/en-us/visualstudio/ide/managing-external-tools?view=vs-2019

**Comment by mrlacey** [comment]
Because the extension works with files that aren't part of a solution, (or even a project) I don't think it's appropriate to try and handle everything that VS supports with external tools.

Replacing `$(ItemPath)` with the path of the file should be quite straightforward.

This should probably also be case insensitive too.

**Comment by mrlacey** [comment]
`$(ItemPath)` is supported as part of a file name/path as of version 3.0 (in the marketplace now).
