### ISSUE TITLE
Clicking a link in the "Peek Definition" frame makes the original focus jump

### ISSUE THREAD

**Issue by skhrshin** [mrlacey/CommentLinks#52]
## Overview

When you right click an identifier and select "Peek Definition", a frame showing the code around the definition appears. Even in that frame, you can click a link button generated by Comment Links, but then the frame doesn't scroll to the position the link references to and the focus within the editor window which the definition is originally peeked from jumps to that position instead.

## Steps to reproduce

```cpp
#include <iostream>

// link:v:main
int xyz = 0;

//
//
//

int main() {
    std::cout << xyz << std::endl;
}
```

1. Prepare a source file with the code above
2. Open the source file
3. Right click `xyz` within `int xyz = 0`
4. Select "Peek Definition"
5. Make sure that a frame is opened and its focus is at `int xyz = 0;`
6. Click the link button in the opened frame

## Expected behavior

The focus in the opened frame jumps to the line `int main() {`.

## Actual behavior

The focus in the editor window jumps to the line `int main() {`.

## Tested versions

Visual Studio Community 2022 (64-bit) 17.7.1
Comment Links 2.15

**Comment by mrlacey** [comment]
There aren't (as far as I can find) APIs for determining if the link button is being displayed in a "peek" window (or elsewhere) or ways to influence the contents of a peeked window or change it's contents.
Without this there isn't a way to limit the buttons display or which actions it can act upon when displayed in a peek window.

Instead, I'm going to change things so that links are only shown in the main editor window.
This means that links will no longer show up in the peek window.
It also means they won't appear in random other places too. (Such as the diff or output windows.)

**Comment by mrlacey** [comment]
Changes to the highlighting of links within the peek window have changed as of version 3.0 (in the marketplace now).
